name: CI
on: [push]

jobs:

  deploy_presentation:
    name: Make and deploy presentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Make documentation
        run: |
          make build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: presentation
